// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moeen.Api.infrastructure.Data;

#nullable disable

namespace Moeen.Api.infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HalqeSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaturdayLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HalqeSessionId");

                    b.HasIndex("SaturdayLessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("juz_form")
                        .HasColumnType("int");

                    b.Property<int>("juz_to")
                        .HasColumnType("int");

                    b.Property<int>("mark")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Fouj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("End_time")
                        .HasColumnType("time");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.ToTable("Foujs");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Halqa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoujId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoujId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Halqas");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.HalqaSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HalqaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("end_time")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("start_time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("HalqaId");

                    b.ToTable("HalqaSessions");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Mosque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mosques");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.PdfFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaturdayLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uploaded_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.HasIndex("SaturdayLessonId");

                    b.ToTable("PdfFiles");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.PosInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PosInteractions");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HalqaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("juz_number")
                        .HasColumnType("int");

                    b.Property<int>("level_score")
                        .HasColumnType("int");

                    b.Property<int>("memorized_until")
                        .HasColumnType("int");

                    b.Property<int>("next_target")
                        .HasColumnType("int");

                    b.Property<int>("page_number")
                        .HasColumnType("int");

                    b.Property<Guid>("studentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HalqaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("studentId");

                    b.ToTable("ProgressEntries");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayHalqa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("age_max")
                        .HasColumnType("int");

                    b.Property<int>("age_min")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("SaturdayHalqes");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaturdayHalqeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("end_time")
                        .HasColumnType("time");

                    b.Property<int>("lesson_number")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("start_time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("MosqueId");

                    b.HasIndex("SaturdayHalqeId");

                    b.ToTable("SaturdayLesson");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("font_size")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joinef_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("theme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Student", b =>
                {
                    b.HasBaseType("Moeen.Api.Core.Entities.User");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaturdayHalqaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaturdayHalqeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("enrollmrnt_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasIndex("MosqueId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SaturdayHalqaId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Supervisor", b =>
                {
                    b.HasBaseType("Moeen.Api.Core.Entities.User");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("datetime2");

                    b.HasIndex("MosqueId");

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Teacher", b =>
                {
                    b.HasBaseType("Moeen.Api.Core.Entities.User");

                    b.Property<Guid>("MosqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("assigned_at")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("boi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("MosqueId");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Attendance", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.HalqaSession", "HalqeSession")
                        .WithMany("Attendances")
                        .HasForeignKey("HalqeSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.SaturdayLesson", "SaturdayLesson")
                        .WithMany("attendances")
                        .HasForeignKey("SaturdayLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Teacher", "Teacher")
                        .WithMany("Attendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HalqeSession");

                    b.Navigation("SaturdayLesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Complaint", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", "User")
                        .WithMany("complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Exam", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Fouj", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("foujs")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Halqa", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Fouj", "Fouj")
                        .WithMany("Halqas")
                        .HasForeignKey("FoujId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Teacher", "Teacher")
                        .WithMany("halaqas")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fouj");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.HalqaSession", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Halqa", "Halqa")
                        .WithMany("HalqeSessions")
                        .HasForeignKey("HalqaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Halqa");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.PdfFile", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("pdfFiles")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.SaturdayLesson", "SaturdayLesson")
                        .WithMany("PdfFiles")
                        .HasForeignKey("SaturdayLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");

                    b.Navigation("SaturdayLesson");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.PosInteraction", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Post", "Post")
                        .WithMany("PosInteractions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.User", "User")
                        .WithMany("PosInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Post", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("posts")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.ProgressEntry", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Halqa", "Halqa")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("HalqaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Teacher", "Teacher")
                        .WithMany("ProgressEntrys")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Student", "Student")
                        .WithMany("progressEntrys")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Halqa");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayHalqa", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayLesson", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.Mosque", null)
                        .WithMany("SaturdayLessons")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Moeen.Api.Core.Entities.SaturdayHalqa", "SaturdayHalqe")
                        .WithMany("SaturdayLessons")
                        .HasForeignKey("SaturdayHalqeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SaturdayHalqe");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Student", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Moeen.Api.Core.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("Students")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Student", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Moeen.Api.Core.Entities.SaturdayHalqa", "SaturdayHalqa")
                        .WithMany("Students")
                        .HasForeignKey("SaturdayHalqaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");

                    b.Navigation("Parent");

                    b.Navigation("SaturdayHalqa");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Supervisor", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Moeen.Api.Core.Entities.Supervisor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("supervisors")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Teacher", b =>
                {
                    b.HasOne("Moeen.Api.Core.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Moeen.Api.Core.Entities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moeen.Api.Core.Entities.Mosque", "Mosque")
                        .WithMany("Teachers")
                        .HasForeignKey("MosqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mosque");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Fouj", b =>
                {
                    b.Navigation("Halqas");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Halqa", b =>
                {
                    b.Navigation("HalqeSessions");

                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.HalqaSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Mosque", b =>
                {
                    b.Navigation("SaturdayLessons");

                    b.Navigation("Students");

                    b.Navigation("Teachers");

                    b.Navigation("foujs");

                    b.Navigation("pdfFiles");

                    b.Navigation("posts");

                    b.Navigation("supervisors");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Post", b =>
                {
                    b.Navigation("PosInteractions");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayHalqa", b =>
                {
                    b.Navigation("SaturdayLessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.SaturdayLesson", b =>
                {
                    b.Navigation("PdfFiles");

                    b.Navigation("attendances");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.User", b =>
                {
                    b.Navigation("PosInteractions");

                    b.Navigation("complaints");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Children");

                    b.Navigation("Exams");

                    b.Navigation("progressEntrys");
                });

            modelBuilder.Entity("Moeen.Api.Core.Entities.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ProgressEntrys");

                    b.Navigation("halaqas");
                });
#pragma warning restore 612, 618
        }
    }
}
